<div class="container-fluid">
	<?php if(isset($newChat)) echo "Você iniciou uma conversa com o Administrador. Chat #$newChat"; ?>
	<hr>

	<div>
		<textarea class="form-control" id="chatscreen" name="chatscreen" readonly></textarea>
	</div>
	<div>
		<input type="text" class="form-control" id="typemsg" name="typemsg" placeholder="digite aqui">
	</div>
	<div>
		<button class="btn btn-primary" onClick="send()">Enviar</button>
	</div>

</div>


<script type="text/javascript">
	function send()
	{
		$.ajax({
			type: "post",
			url: "<?= $this->url('chat-send'); ?>",
			datatype: "json",
			data: {typemsg:(document.getElementById('typemsg').value)},
			success: function(data) {
				alert(data);
			}
		});
	}

	function display()
	{
		$.ajax({
			type: "POST",
			url: "<?= $this->url('chat-display'); ?>",
			datatype: "text/html",
		});
	}
</script>

