<div class="container-fluid">
	<div class="panel">
		<div class="panel-heading register-form-title">Postar uma foto <span class="fa fa-file-image-o"></span></div>
		<div class="panel-body register-form-body">
			<center>
				<form action="" method="POST" enctype="multipart/form-data">
					<div><label>Digite um título para a foto (não obrigatório)<input name="image_title" type="text" maxlength=100 class="form-control"></label></div>

					<div><label>Escolha a imagem <input name="image_url" type="file" required="required">
					</label></div>
					<hr>

					<div>
						<button type="submit" class="btn btn-lg btn-primary">Postar imagem <span class="fa fa-file-image-o"></span></button>
					</div>
				</form>
			</center>
		</div>
	</div>
</div>