
<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading register-form-title">Gerenciador de Imagens <span class="fa fa-file-image-o"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                	<th class="text-center">Título</th>
                    <th class="text-center">Url (caminho)</th>                                        
                    <th class="text-center">Está disponível?</th>                    
                    <th class="text-center">Alterar Disponibilidade</th>
                    <th class="text-center">Apagar</th>
                    
                    <?php if(empty($images)): ?>
                        <tr>
                            <center>
                                <h2>Sem imagens no momento! <span class="fa fa-file-image-o"></span></h2>
                            </center>
                        </tr>
                    <?php endif; ?>

                    <?php foreach($images as $image): ?>
                        <tr>                        
                            <td class="text-center"><?= $image->getImageTitle(); ?> <span class="fa fa-file-image-o"></span></td>    
                            <td class="text-center"><?= $image->getImageUrl(); ?></td>
                            <td class="text-center">
                            	<span style="<?= ($image->getImageActive()) ? 'color: green' : 'color: red'; ?>" class="<?= ($image->getImageActive()) ? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove'?>"></span>
                            </td>
                            <td class="text-center">
                            	<a href="<?= $this->url('images-toggle', array('id' => $image->getImageId())); ?>">
                            		<button class="btn btn-primary"><?= ($image->getImageActive()) ? 'Desativar' : 'Ativar'; ?></button>
                            	</a>
                            </td>
                            <td class="text-center">
                            	<a href="<?= $this->url('images-delete', array('id' => $image->getImageId())); ?>">
                            		<button class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></button>
                            	</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>                    
                </table>
                <a href="<?= $this->url('images-add'); ?>">
                	<center>
                		<button class="btn btn-lg btn-success">Postar foto <span class="fa fa-file-image-o"></span></button>
                	</center>
                </a>
            </div>
         </div>
    </div>
</div>