<div class="container-fluid">
    <div class="panel" style="max-width: 1200px!important">
        <div class="panel-heading register-form-title">Lista de Notícias do Site <span class="fa fa-newspaper-o"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <th class="text-center">Título da Notícia</th>
                    <th class="text-center">Data de Postagem</th>                    
                    <th class="text-center">Visualizar Notícia</th>                    
                    
                    <?php foreach($news as $noticia): ?>
                        <tr>
                            <td class="text-center"><?= $noticia->getNewsTitle(); ?></td>
                            <td class="text-center"><?= $noticia->getNewsDate()->format('d/m/Y - H:i:s'); ?></td>
                            <td class="text-center">
                                <a href="<?= $this->url('news-view', array('id' => $noticia->getNewsId())); ?>">
                                    <button class="btn"><span class="fa fa-newspaper-o"></span></button>
                                </a>                                
                            </td>                           
                        </tr>
                    <?php endforeach; ?>
                    
                </table>
            </div>
         </div>
    </div>
</div>