<script type="text/javascript">
$('comments-container').hide();

function toggle(element)
{   
    $(element).is(":visible") ? $(element).slideUp(500) : $(element).slideDown(500);
}

</script>

<div>    
        <div class="container-fluid">
            <div class="news-title"><?= $noticia->getNewsTitle(); ?></div>
            <div class="container-fluid news-container">                
                <p>Postada em <?= $noticia->getNewsDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsDate()->format('H:i'); ?> <span class="glyphicon glyphicon-time"></span> <?php if($noticia->getNewsEditDate() != null):?>|
                    Atualizado em <?= $noticia->getNewsEditDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsEditDate()->format('H:i'); ?> <span style="color: green" class="glyphicon glyphicon-ok"></span>
                <?php endif; ?></p>            
                <br>
                
                <div class="news-font">
                    <?= htmlspecialchars_decode($noticia->getNewsContent()); ?>
                </div>
                
                <div class="news-source">
                    <b>Fonte: <i><a href="<?= $noticia->getNewsSource(); ?>"><?= $noticia->getNewsSource(); ?></a></i></b>
                </div>
                <br>
                
                <center>                    
                        <button type="button" class="btn btn-info" onClick="toggle('<?= "#comment_panel_".$noticia->getNewsId(); ?>')">
                            Comentários(<?php echo count($comentarios); ?>) <span style="color: blue" class="glyphicon glyphicon-comment"></span>
                        </button>
                </center>
                
                <hr>               
                
                
                <div class="container-fluid comments-container form-group" id="<?= 'comment_panel_'.$noticia->getNewsId(); ?>">                   
                        <center>
                            <form class="panel" method="POST" action="<?= $this->url('comments-add'); ?>">
                                <div class="register-form-title">Digite seu comentário abaixo</div>
                                <div class="register-form-body">
                                    <div>        
                                        <input name="comment_news" type="hidden" value="<?= $noticia->getNewsId(); ?>">                            
                                        <label>Digite seu nome                                
                                            <input required="required" name="comment_author" type="text" class="form-control">
                                        </label>                                        
                                    </div>                                  
                                    
                                    <div>
                                        <label>Digite seu comentário
                                            <textarea name="comment_content" required="required" class="form-control"></textarea>
                                        </label>                            
                                    </div>
                                    
                                    <div><button type="submit" class="btn btn-primary">Comentar</button></div>
                               </div>
                            </form>
                        </center>  
                        <hr>                    
                        
                            <?php foreach($comentarios as $comment): ?>
                                <p><span style="font-size: 20px" class="glyphicon glyphicon-user"></span> <?= $comment->getCommentAuthor();?> comentou:</p>                                
                                <?= $comment->getCommentContent(); ?>p                                
                                <hr>
                            <?php endforeach; ?>
                                                                 
                </div>                
                
                <center>
                    
                </center>
                
                
                <hr>                           
                <br><br><br>
             </div>         
         </div> 
    
</div>
