    <div class="container-fluid">
        <div class="news-title"><?= $noticia->getNewsTitle(); ?></div>
        <div class="container-fluid news-container">                
            <p>Postada em <?= $noticia->getNewsDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsDate()->format('H:i'); ?> <span class="glyphicon glyphicon-time"></span> <?php if($noticia->getNewsEditDate() != null):?>|
                Atualizado em <?= $noticia->getNewsEditDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsEditDate()->format('H:i'); ?> <span style="color: green" class="glyphicon glyphicon-ok"></span>
            <?php endif; ?></p>            
            <br>
            
            <div class="news-font">
                <?= htmlspecialchars_decode($noticia->getNewsContent()); ?>
            </div>
            
            <div class="news-source">
                <b>Fonte: <i><a href="<?= $noticia->getNewsSource(); ?>"><?= $noticia->getNewsSource(); ?></a></i></b>
            </div>
            <hr>
         </div>
     </div>
