<center>
    <div class="panel" style="text-align: center">
        <div class="panel-heading register-form-title">Acesso ao Sistema <span class="glyphicon glyphicon-user"></span></div>
        <div class="panel-body register-form-body">    
            <?= $this->form()->openTag($loginForm); ?>
            <div><?= $this->formrow($loginForm->get('user_login')); ?></div>
            <div><?= $this->formrow($loginForm->get('user_password')); ?></div>
            <br>
            <div><button type="submit" class="btn btn-lg btn-info" >Autenticar <span class="fa fa-check"></span></button></div>
            <?= $this->form()->closeTag(); ?>        
        </div>
    </div>
</center>