<div class="container-fluid">	
		<?= htmlspecialchars_decode($system->getInfoContent()); ?>
	<hr>
	<br>
	<center>
	<div class="panel" style="max-width: 550px">
		<div class="panel-heading register-form-title">Contrate o consultor <span class="fa fa-thumbs-o-up"></span></div>
		<div class="panel-body register-form-body">			
			<center>							
				<form action="" method="POST">
					<div>
                    	<label>Email
                    		<input name="request_email" type="email" required="required" class="form-control" style="min-width: 300px">
                    	</label>
                    </div>
					<div>
                     	<label>Digite sua solicitação
                        	 <textarea name="request_content" required="required" class="form-control comment-input" style="min-width: 400px; min-height: 150px"></textarea>
                        </label>                            
                    </div>
                    <hr>

                    <div>
                    	<button type="submit" class="btn btn-success">
                    		Enviar Solicitação <span class="glyphicon glyphicon-ok"></span>
                    	</button>
                    </div>                    
				</form>

			</center>
		</div>
	</div>
	</center>
</div>