<form action="" method="POST">
	<div class="standard-title">Adicionar um vídeo <span class="glyphicon glyphicon-facetime-video"></span></div>
	<hr>

	<div><input type="text" class="form-control" name="video_title" placeholder="Título do vídeo" required="required"></div>
	<br>
	<div><input type="text" class="form-control" name="video_url" placeholder="Link do vídeo" required="required"></div>
	<hr>

	<center>	
		<button type="submit" class="btn btn-primary">Adicionar vídeo <span class="glyphicon glyphicon-facetime-video"></span></button>
	</center>
</form>