<div class="container-fluid">
	<div class="panel">
		<div class="panel-heading register-form-title">Faça uma pergunta! <span class="glyphicon glyphicon-question-sign"></span></div>
		<div class="panel-body register-form-body">
			<center>
				<div><?= $this->form()->openTag($questionForm); ?></div>
				<div><?= $this->formrow($questionForm->get('question_author')); ?></div>
				<div><?= $this->formrow($questionForm->get('question_author_email')); ?></div>
				<div><?= $this->formrow($questionForm->get('question_title')); ?></div>				
				<div>
					<button type="submit" class="btn btn-lg btn-success">Perguntar <span class="glyphicon glyphicon-question-sign"></span></button>
				</div>
				
				<div><?= $this->form()->closeTag(); ?></div>
				<hr>				
			</center>
		</div>
	</div>
</div>