<center>
<div class="panel" style="max-width: 600px">
	<div class="panel-heading register-form-title">Perguntas e Respostas <span class="glyphicon glyphicon-question-sign"></span></div>
	<div class="panel-body register-form-body">
		<?php if(empty($questions)): ?>
			<center>
				<div style="font-family: Times New Roman; font-size: 25px;">
					<p>Sem perguntas no momento.</p>
					<hr>
					
					<p>
						<a href="<?= $this->url('questions-add'); ?>">
							<button class="btn btn-lg btn-primary">Faça uma pergunta <span class="glyphicon glyphicon-question-sign"></span></button>
						</a>
					</p>

				</div>
			</center>
		<?php endif; ?>
		<?php foreach($questions as $question): ?>
			<p>Pergunta feita por <b><?= $question[0]->getQuestionAuthor(); ?></b> em <?= $question[0]->getQuestionDate()->format('d/m/Y - H:i:s'); ?> <span class="glyphicon glyphicon-time"></span></p>
			
			<p><b>- <?= $question[0]->getQuestionTitle(); ?></b></p>
			<br>			
			<p><span class="glyphicon glyphicon-arrow-right"></span> <?= $answers[$question[0]->getQuestionId()][0]->getAnswerContent(); ?></p>

			<hr>
		<?php endforeach; ?>
	</div>
</div>
</center>