<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading register-form-title">Gerenciador de Perguntas <span class="glyphicon glyphicon-question-sign"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <?php if(empty($questions)): ?>
                    <center>
                        <h2>Sem perguntas no momento.</h2>
                    </center>
                <?php endif; ?>
                <table class="table table-striped table-bordered">
                	<th class="text-center">Autor</th>
                    <th class="text-center">Email do Autor</th>                                        
                    <th class="text-center">Data</th>                    
                    <th class="text-center">Respondida?</th>
                    <th class="text-center">Visualizar</th>                    
                    <th class="text-center">Responder</th>
                    <th class="text-center">Apagar</th>

                    <?php foreach($questions as $question): ?>
                        <tr>
                            <td class="text-center"><?= $question->getQuestionAuthor(); ?></td>
                            <td class="text-center"><?= $question->getQuestionAuthorEmail(); ?></td>
                            <td class="text-center"><?= $question->getQuestionDate()->format('d/m/Y - H:i:s');?></td>
                            <td class="text-center">                                
                                <span style="<?= (empty($answers[$question->getQuestionId()])) ? 'color: red' : 'color: green'; ?>">
                                <?= (empty($answers[$question->getQuestionId()])) ? 'Não' : 'Sim' ?>
                                </span>
                            </td>
                            <td class="text-center">
                                <a href="#" data-toggle="modal" data-target="<?= '#question_'.$question->getQuestionId() ?>">
                                    <span style="color: blue" class="glyphicon glyphicon-list-alt"></span>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="<?= $this->url('questions-reply', array('id' => $question->getQuestionId())); ?>">
                                    <span style="color: green" class="glyphicon glyphicon-share-alt"></span>
                                </a>
                            </td> 
                            <td class="text-center">
                                <a href="<?= $this->url('questions-delete', array('id' => $question->getQuestionId())); ?>">
                                    <span style="color: red" class="glyphicon glyphicon-remove"></span>
                                </a>
                            </td>  
                            
                        </tr>
                    <?php endforeach; ?>

                </table>
            </div>
        </div>
    </div>
</div>

<?php foreach($questions as $question): ?>
    <div class="modal fade" id="<?= 'question_'.$question->getquestionId(); ?>">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header standard-title">
                    <center>
                        <p>Autor: <b><?= $question->getQuestionAuthor(); ?></b> <span class="glyphicon glyphicon-user"></span></p>
                        <p>Email do Autor: <b><?= $question->getQuestionAuthorEmail(); ?></b> <span class="glyphicon glyphicon-envelope"></span>
                    </center>
                </div>
                <div class="modal-body">
                    <?= $question->getQuestionTitle(); ?>                    
                    <hr>
                        <?php if(empty($answers[$question->getQuestionId()])): ?>
                            <center><h2>Resposta não disponível</h2></center>
                        <?php else: ?>                            
                            <?= $answers[$question->getQuestionId()][0]->getAnswerContent(); ?>
                        <?php endif; ?>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>