<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading register-form-title">Resposta à pergunta <span class="glyphicon glyphicon-share-alt"></span></div> 
        
        <div class="panel-body register-form-body">
        	<?= $question->getQuestionTitle(); ?>
        	<hr>
        	
        	<p>Autor: <b><?= $question->getQuestionAuthor(); ?></b> <span class="glyphicon glyphicon-user"></span></p>
        	<p>Email do Autor: <b><?= $question->getQuestionAuthorEmail(); ?></b> <span class="glyphicon glyphicon-envelope"></span></p>
        	<hr>

        	<form action="" method="POST">
	        	<center>
		        	<label>Resposta
		        		<textarea required="required" name="answer_content" class="form-control" style="max-width: 800px; min-width: 500px; min-height: 150px"></textarea>    
		        	</label>
	        	<hr>
	        		<button type="submit" class="btn btn-lg btn-primary">Responder <span class="glyphicon glyphicon-share-alt"></span></button>
	        	</center>
	        </form>

        </div>
    </div>
</div>