<div class="container-fluid">
    <div class="panel" style="max-width: 1200px!important">
        <div class="panel-heading register-form-title">Gerenciador de Notícias <span class="fa fa-newspaper-o"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <th class="text-center">Título da Notícia</th>
                    <th class="text-center">Data de Criação</th>
                    <th class="text-center">Data de Edição</th>
                    <th class="text-center">Autor</th>
                    <th class="text-center">Fonte</th>
                    <th class="text-center">Editar Notícia</th>
                    <th class="text-center">Situação</th>
                    <th class="text-center">Alterar Situação</th>
                    <th class="text-center">Apagar</th>
                    
                    <?php foreach($news as $noticia): ?>
                        <tr>
                            <td class="text-center"><?= $noticia->getNewsTitle(); ?></td>
                            <td class="text-center"><?= $noticia->getNewsDate()->format('d/m/Y - H:i:s'); ?></td>
                            <td class="text-center"><?= ($noticia->getNewsEditDate() == null) ? "Sem edições!" : $noticia->getNewsEditDate()->format('d/m/Y - H:i:s'); ?></td>
                            <td class="text-center"><?= $noticia->getNewsAuthor()->getUserName(); ?> <span class="glyphicon glyphicon-user"></span></td>
                            <td class="text-center"><?= $noticia->getNewsSource(); ?></td>
                            <td class="text-center">
                                <a href="<?= $this->url('news-edit', array('id' => $noticia->getNewsId())); ?>">
                                    <button class="btn"><span class="fa fa-newspaper-o"></span></button>
                                </a>                                
                            </td> 
                            <td class="text-center <?= ($noticia->getNewsPublished()) ? 'success' : "warning" ?>">
                                <?= ($noticia->getNewsPublished()) ? "Publicada" : "Não Publicada"?>                                
                            </td>    
                            <td>
                                <a href="<?= $this->url('news-publish', array('id' => $noticia->getNewsId())); ?>">
                                    <button class="<?= (!$noticia->getNewsPublished()) ? 'btn btn-success' : "btn btn-warning" ?>">
                                    <?= (!$noticia->getNewsPublished()) ? 'Publicar' : "Despublicar" ?>
                                    </button>
                                </a>
                            </td>
                            <td> 
                                <a href="<?= $this->url('news-delete', array('id' => $noticia->getNewsId())); ?>">
                                    <button class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></button>
                                </a>                                                                      
                            </td>
                        </tr>
                    <?php endforeach; ?>                    
                </table>

                <center>
                    <a href="<?= $this->url('news-create'); ?>">
                        <button class="btn btn-lg btn-success">Postar notícia <span class="glyphicon glyphicon-paperclip"></span>
                        </button>
                    </a>
                </center>

            </div>
         </div>
    </div>
</div>