<div class="container-fluid">
	<div class="panel">
		<div class="panel-heading register-form-title">Cadastrar Patrocinador <span class="glyphicon glyphicon-bookmark"></span></div>
		<div class="panel-body register-form-body">
			<center>
				<form action="" method="POST" enctype="multipart/form-data">
					<div><label>Digite um título para o patrocinador <input name="patrocinador_name" type="text" maxlength=100 class="form-control" required="required"></label></div>
					<br>
					<div><label>Escolha a imagem do patrocinador <input name="patrocinador_url" type="file" required="required">
					</label></div>
					<hr>

					<div>
						<button type="submit" class="btn btn-lg btn-primary">Cadastrar Patrocinador <span class="glyphicon glyphicon-bookmark"></span></button>
					</div>
				</form>
			</center>
		</div>
	</div>
</div>