<div class="container-fluid">
	<div class="panel">
		<div class="panel-heading register-form-title">Editar Patrocinador <b>"<?= $patrocinador->getPatrocinadorName(); ?>"</b> <span class="glyphicon glyphicon-bookmark"></span></div>
		<div class="panel-body register-form-body">
			<center>
				<form action="" method="POST" enctype="multipart/form-data">

					Posição ocupadas por patrocinadores: <b>[
					<?php foreach($patrocinadores as $p): ?>
						<?= $p->getPatrocinadorPosition(); ?>
						<?php if($p != $patrocinadores[count($patrocinadores) - 1]): ?>
							<?= ", ";?> 
						<?php endif; ?>
					<?php endforeach; ?>]</b>
					<hr>

					<div><label>Digite um título para o patrocinador <input name="patrocinador_name" type="text" maxlength=100 class="form-control" required="required" value="<?= $patrocinador->getPatrocinadorName(); ?>"></label></div>
					<br>
					
					<div><label>Escolha a posição de exibição do patrocinador
						<input name="patrocinador_position" type="number" min="1" step="1" class="form-control" required="required" value="<?= $patrocinador->getPatrocinadorPosition(); ?>">
					</label></div>

					<hr>

					<div>
						<button type="submit" class="btn btn-lg btn-primary">Atualizar Patrocinador <span class="glyphicon glyphicon-ok"></span></button>
					</div>
				</form>
			</center>
		</div>
	</div>
</div>