<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Custom CSS -->
        <link href="css/simple-sidebar.css" rel="stylesheet">        

        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Limelight' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/site.css'))
                        ->prependStylesheet($this->basePath("css/font-awesome.min.css"))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/angular.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/ckeditor/ckeditor.js'))
        ; ?>

        <div class="container-fluid header">
            <div class="container-fluid" style="padding-top: 1.5%; padding-left: 5%;">              
                    
                <div class="header-text" style="font-size: 60px; font-family: 'TrajanPro-Regular', sans-serif!important;">WELINGTON MAPURUNGA</div>

                <div class="header-text" style="font-size: 36.5px; font-family: 'TrajanPro-Original', sans-serif!important;">Consultoria Previdenciária Especializada</div>                         
            </div>
        </div>

    </head>        
    

    <nav class="navbar navbar-default navbar-inverse" role="navigation" style="background-color: black; border-radius: 0px; ">
            <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">                
              </a>              
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                    <li><a class="topbar-item" href="<?= $this->url('home'); ?>">Início <span class="glyphicon glyphicon-home"></span></a></li>
                    <li><a class="topbar-item" href="<?= $this->url('news-all'); ?>">Notícias <span class="glyphicon glyphicon-th-list"></span></a></li>
                    <li><a class="topbar-item" href="#">Artigos e Eventos <span class="glyphicon glyphicon-book"></span></a></li>
                    <li><a class="topbar-item" href="#">Vídeos  <span class="glyphicon glyphicon-facetime-video"></span></a></li>
                    <li><a class="topbar-item" href="#">Currículo <span class="glyphicon glyphicon-file"></span></a></li>
              </ul> 

              <ul class="nav navbar-nav navbar-right">
                    <?php if($this->identity()): ?>
                        <li>
                            <span class="dropdown">
                                <a href="#" style="text-decoration: none!important; color: white!important" class="dropdown-toggle" style="" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-user"></span> 
                                    <?= $this->identity()->getUserName(); ?> <span class="fa fa-caret-down"></span>
                                </a>                            
                                                             
                                <ul class="dropdown-menu">                                    
                                    <li><a href="<?php echo $this->url('users'); ?>">Controle de Usuários <span style="color: green" class="glyphicon glyphicon-user"></span></a></li>
                                    
                                    <li><a href="<?php echo $this->url('news'); ?>">Controle de Notícias <span style="color: #3399ff" class="fa fa-newspaper-o"></span></a></li>

                                    <li><a href="<?php echo $this->url('comments'); ?>">Controle de Comentários <span style="color: #21A3CF" class="glyphicon glyphicon-comment"></span></a></li>
                                    
                                    <li><a href="<?php echo $this->url('users-logout'); ?>">Sair <span style="color: red" class="glyphicon glyphicon-remove"></span></a></li>
                                </ul>
                            </span>
                        </li>
                    <?php endif; ?>
              </ul>

            </div>
          </div>
    </nav>
    
    <div class="container-fluid" style="">
         <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

        <!-- Wrapper for slides -->
           <div class="carousel-inner" role="listbox">
              <?php foreach($images as $image): ?>
                <div class="<?= ($image == $images[0]) ? 'item active' : 'item'; ?>">
                    <img src="<?= $this->basePath('img/'.$image->getImageUrl());?>" >
                </div>                 
              <?php endforeach; ?>              
           </div>

        <!-- Left and right controls -->
             <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
</div>       

     <hr>      
    
    <body>   
        <div class="col-md-2">           
            <div id="sidebar" role="navigation">           
                <ul class="nav nav-sidebar">
                  <li class="active">
                        <a style="text-align: center; text-decoration: none!important" href="#">
                            --
                        </a>
                  </li>                  
                </ul>                
            </div>         
        </div><!--/span-->
        
               
      
        
        <div class="col-md-7">   
            
            <?= $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
            <?= $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
            <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
                  
            <?php echo $this->content; ?>

        </div>   

         <div class="col-md-3">         
              <div class="container-fluid">                   
                <div id="sidebar" role="navigation">           
                  <ul class="nav nav-sidebar">
                    
                        <li style="word-wrap: break-word!important; margin: 0" class="active">
                            <a style="text-align: center; text-decoration: none!important; word-wrap: break-word" href="#">Patrocinadores</a>
                         </li>

                        <li></li>                        

                        <li style="word-wrap: break-word!important; text-align: center!important;">
                            <img id="banner" class="img-responsive" style="max-width: 300px;" src="">
                        </li>
                    
                  </ul>                
              </div>   
            </div>
         </div> 
         
         <br><br><br><br><br><br><br><br><br><br>
        
        
    </body> 

     

</html>         