<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Custom CSS -->
        <link href="css/simple-sidebar.css" rel="stylesheet">        

        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Limelight' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/site.css'))
                        ->prependStylesheet($this->basePath("css/font-awesome.min.css"))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <div class="container-fluid header">
            <div class="container" style="padding-top: 1.5%; padding-left: 5%;"> 
                
                <div style="font-family: Times New Roman; font-size: 45px; float: left; margin-top: 0;">              
                </div> 
                    
                <div class="header-text" style="font-size: 60px; font-family: 'TrajanPro-Regular', sans-serif!important;">WELINGTON MAPURUNGA</div>

                <div class="header-text" style="font-size: 36.5px; font-family: 'TrajanPro-Original', sans-serif!important;">Consultoria Previdenciária Especializada</div>                         
            </div>
        </div>

    </head>        
    

    <nav class="navbar navbar-default navbar-inverse" role="navigation" style="background-color: black; border-radius: 0px; ">
            <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">                
              </a>              
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                    <li><a class="topbar-item" href="<?= $this->url('home'); ?>">Início <span class="glyphicon glyphicon-home"></span></a></li>
                    <li><a class="topbar-item" href="#">Notícias <span class="glyphicon glyphicon-th-list"></span></a></li>
                    <li><a class="topbar-item" href="#">Artigos e Eventos <span class="glyphicon glyphicon-book"></span></a></li>
                    <li><a class="topbar-item" href="#">Vídeos  <span class="glyphicon glyphicon-facetime-video"></span></a></li>
                    <li><a class="topbar-item" href="#">Currículo <span class="glyphicon glyphicon-file"></span></a></li>
              </ul> 

              <ul class="nav navbar-nav navbar-right">
                    <?php if($this->identity()): ?>
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span> <?= $this->identity()->getUserName(); ?> <span class="fa fa-caret-down"></span></a></li>
                    <?php endif; ?>
              </ul>

            </div>
          </div>
    </nav>
    
    <div class="container-fluid" style="">
        <div class="row">
            <div id="myCarousel" class="carousel slide carousel-main" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner carousel-img" role="listbox">
                <div class="item active">
                  <img class="img-responsive carousel-img" src="<?= $this->basePath('img/carousel/fortaleza1.jpg'); ?>" alt="Chania">
                </div>    
                <div class="item">
                  <img class="img-responsive carousel-img" src="<?= $this->basePath('img/carousel/fortaleza2.jpg'); ?>" alt="Chania">
                </div> 
                <div class="item">
                  <img class="img-responsive carousel-img" src="<?= $this->basePath('img/carousel/fortaleza3.jpg'); ?>" alt="Chania">
                </div>
                <div class="item">
                  <img class="img-responsive carousel-img" src="<?= $this->basePath('img/carousel/fortaleza4.jpg'); ?>" alt="Chania">
                </div>   
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </div>

        </div>

     <hr>      
    
    <body onLoad="">
        
         <?= $this->content; ?> 
        
        <div class="col-md-2">           
            <div id="sidebar" role="navigation">           
                <ul class="nav nav-sidebar">
                  <li class="active"><a style="text-align: center; text-decoration: none!important" href="#">Artigos e Eventos</a></li>                  
                </ul>                
            </div>         
        </div><!--/span-->
        
         <div class="container-fluid">      
      
        
        
        <div class="col-md-7">   
            
            <?= $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
            <?= $this->flashMessenger()->render('info', array('alert', 'alert-info')); ?>
            <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
                  
            <div class="news-title">Notícias Relacionadas a Direito Previdenciário</div>
            
            <div class="container-fluid news-container">                
                <p>Postada em 21/01/2016 as 07:52pm <span class="glyphicon glyphicon-time"></span></p>
                
                <br>
                
                <div class="news-font">
                    Anualmente a Receita Federal define, por meio de parâmetros, quais as Pessoas Físicas e Jurídicas que estarão sujeitas ao acompanhamento diferenciado da fiscalização fazendária. As regras estão em três normas, a saber: a) · Portaria RFB nº 641, de 11 de maio de 2015; b) Portaria RFB nº 1.754, de 24 de dezembro de 2015 (Pessoas Físicas Diferenciadas) e c) Portaria RFB nº 1.755, de 24 de dezembro de 2015 (Pessoas Jurídicas Diferenciadas). Read More »
                </div> 
            </div>            
            <hr>               

            <div class="news-title">Another News from Website</div>
                <div class="container-fluid news-container">
                        <p>Postada em 20/01/2016 as 11:52am <span class="glyphicon glyphicon-time"></span></p>                
                <br>

                    <div class="news-font">
                        Anualmente a Receita Federal define, por meio de parâmetros, quais as Pessoas Físicas e Jurídicas que estarão sujeitas ao acompanhamento diferenciado da fiscalização fazendária. As regras estão em três normas, a saber: a) · Portaria RFB nº 641, de 11 de maio de 2015; b) Portaria RFB nº 1.754, de 24 de dezembro de 2015 (Pessoas Físicas Diferenciadas) e c) Portaria RFB nº 1.755, de 24 de dezembro de 2015 (Pessoas Jurídicas Diferenciadas). Read More »
                    </div>
                </div>
                
            <br><br><br><br>
            <hr>

            <div class="container-fluid"> <!-- Perguntas e Respostas -->                       
                <div class="panel" style="max-width: 400px;">
                    <div class="panel-heading" style="background-color: #4a685c!important">
                        <center>
                            <div class="questions-title">Perguntas e Respostas <span class="glyphicon glyphicon-question-sign"></span></div>
                        </center>
                    </div>
                    
                    <div class="panel-body questions-body">
                                    <p>O usuário Felipe <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 20/01/2016 as 10:04pm <span class="glyphicon glyphicon-time"></span></b> - <a data-toggle="modal" data-target="#resposta" href="#">Visualizar Resposta</a> <span class="glyphicon glyphicon-ok"></span></p> 
                                    <p>O usuário Welington <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 21/01/2016 as 10:00pm <span class="glyphicon glyphicon-time"></span></b> - <a href="#">Visualizar Resposta</a> <span class="glyphicon glyphicon-ok"></span></p>
                                    <p>O usuário Marcos <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 21/01/2016 as 07:00am <span class="glyphicon glyphicon-time"></span></b> - <span style="color: red">Resposta Não Disponível</span> <span class="glyphicon glyphicon-remove"></span></p>
                    </div>
                    <div class="panel-footer"></div>
                    </div>                        
                </div>                        
            </div>   

        </div><!-- col-md-7 geral -->
    
   

          <div class="col-md-3">         
              <div class="container-fluid">                   
                <div id="sidebar" role="navigation">           
                  <ul class="nav nav-sidebar">
                    
                        <li style="word-wrap: break-word!important; margin: 0" class="active"><a style="text-align: center; text-decoration: none!important; word-wrap: break-word" href="#">Patrocinadores</a></li>

                        <li></li>                        

                        <li style="word-wrap: break-word!important; text-align: center!important;">
                            <img id="banner" class="img-responsive" style="max-width: 300px;" src="">
                        </li>
                    
                  </ul>                
              </div>   
            </div>
         </div>       
          
            
    <div class="modal fade" id="resposta">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <div style="float: right"><a href="#" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span></div></a>
                    <center><h2>Pergunta do Usuário <b>Felipe</b> <span class="glyphicon glyphicon-question-sign"></span>  </h2></center>
                </div>
                <div class="modal-body">
                    <center><h3>Pergunta:</h3></center><hr>
                    <p>TesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTeste ?</p>
                    <p>Autor: Felipe <span class="glyphicon glyphicon-user"></span> - Em: 20/01/2016 as 10:04h <span class="glyphicon glyphicon-time"></span></b></p> 
                </div>
                <div class="modal-footer">
                    <center><label for="texto">Resposta: <textarea style="width: 500px; height: 200px" class="form-control" name="texto" id="texto"></textarea></label>
                    <hr><button onClick="$.ajax({
          type: 'POST',          
          data: {texto: document.getElementById('texto').value},
          url: '<?= $this->url("ajax", array("id" => 1)); ?>',
          success: function(data) {
            alert(data);
          },

          });" class="btn btn-lg btn-info">Responder <span class="glyphicon glyphicon-ok"></span></button></center>
                </div>
            </div>
        </div>
    </div>
        
        
        
    </body> 

     

</html>         