<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Custom CSS -->
        <link href="css/simple-sidebar.css" rel="stylesheet">        
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/site.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    
    <body>
        <center>
            <h1 style="font-family: 'Open Sans', sans-serif;">WELINGTON MAPURUNGA</h1>
            <h1 style="font-family: 'Open Sans', sans-serif;">CONSULTORIA PREVIDENCIÁRIA</h1>            
        </center>

        <nav class="navbar navbar-default" id="topbar" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">                    
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"></a>
                </div>                
                <div class="collapse navbar-collapse">
                    <center><ul class="nav navbar-nav">                        
                        <li class=""><a class="topbar-item" href="<?php echo $this->url('home') ?>">
                            Página Inicial <span class="glyphicon glyphicon-home"></span>
                            </a>
                        </li>
                        <li class=""><a class="topbar-item" href="<?php echo $this->url('home') ?>">
                            Item
                            </a>
                        </li>
                        <li class=""><a class="topbar-item" href="<?php echo $this->url('home') ?>">
                            Item 2
                            </a>
                        </li>
                        <li class=""><a class="topbar-item" href="<?php echo $this->url('home') ?>">
                            Item 3
                            </a>
                        </li>
                        <li class=""><a class="topbar-item" href="<?php echo $this->url('home') ?>">
                            Item 4
                            </a>
                        </li>                           
                    </ul></center>
                </div><!--/.nav-collapse -->
            </div>
        </nav>           

        <div class="container-fluid">            
        <center>        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                      <!-- Indicators -->
                      <ol class="carousel-indicators" style="max-width: 800px; max-height: 600px;">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                        <li data-target="#myCarousel" data-slide-to="3"></li>
                      </ol>

                      <!-- Wrapper for slides -->
                      <div class="carousel-inner" role="listbox">
                        <div class="item active">
                          <img src="https://flyawaysimulation.com/media/images1/images/x-plane-lockheed-l-1011-tristar.jpg" alt="Chania">
                        </div>    
                      </div>

                      <!-- Left and right controls -->
                      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                </div>
            </div>
            </center>            
           
        </div>

        <hr>

        <div class="container-fluid" style="max-width: 100px">    
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav" style="display: inline-block!important">
                    <li class="active">
                        <a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Item 1</a>
                    </li>
                    
                    <li><a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Item 2</a></li>
                    <li><a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Item 3</a></li>
                    <li><a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Item 4</a></li>
                    <li><a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Item 5</a></li>
                </ul>
            </div>
        </div>
            <div class="container-fluid">
                <?php echo $this->content; ?>
                <center><h1 style="display: inline-block!important">Notícias</h1></center>

            
            <div class="navbar navbar-default">
                <center>
                    <h3>Rodapé</h3>
                </center>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>


     

</html>
