<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Custom CSS -->
        <link href="css/simple-sidebar.css" rel="stylesheet">        
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

        <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/site.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <div class="container-fluid" style="background-color: black; color: #fff">
            <div class="row">
                <center>
                    <h1 style="font-family: 'Raleway', sans-serif;">WELINGTON MAPURUNGA</h1>
                    <h1 style="font-family: 'Raleway', sans-serif;">CONSULTORIA PREVIDENCIÁRIA</h1>            
                </center>     
            </div>
        </div>

    </head>
    
    <body>
        <nav class="navbar navbar-default" role="navigation" style="background-color: black; border-radius: 0px">
            <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-center">
                <li><a class="topbar-item" href="#">Início <span class="glyphicon glyphicon-home"></span></a></li>
                <li><a class="topbar-item" href="#">Clientes <span class="glyphicon glyphicon-user"></span></a></li>
                <li><a class="topbar-item" href="#">Sala de Aula <span class="glyphicon glyphicon-road"></span></a></li>
                <li><a class="topbar-item" href="#">Vídeos  <span class="glyphicon glyphicon-facetime-video"></span></a></li>
                <li><a class="topbar-item" href="#">Currículo <span class="glyphicon glyphicon-file"></span></a></li>
              </ul>
              <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Pesquisa...">
              </form>
            </div>
          </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-height: 800px!important">
              <!-- Indicators -->
              <ol class="carousel-indicators" style="max-height: 800px!important">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox" style="max-height: 800px!important">
                <div class="item active">
                  <img src="<?= $this->basePath('img/plane.jpg'); ?>" alt="Chania">
                </div>    
                <div class="item">
                  <img src="<?= $this->basePath('img/firecar.jpg'); ?>" alt="Chania">
                </div>    
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
        </div>

        </div>

     <hr>

<div class="container-fluid">      
      
        <div class="col-md-4">        
            <div id="sidebar" role="navigation">           
                <ul class="nav nav-sidebar">
                  <li class="active"><a class="sidebar-item" href="#">Item 1</a></li>
                  <li><a class="sidebar-item" href="#">Item 2</a></li>
                  <li><a class="sidebar-item" href="#">Item 3</a></li>
                  <li><a class="sidebar-item" href="#">Item 4</a></li>
                </ul>                
            </div> 
            <hr>
            <div id="sidebar" role="navigation">           
                <ul class="nav nav-sidebar">
                  <li class="active"><a style="text-align: center; text-decoration: none!important" href="#">Artigos e Eventos</a></li>
                  <li><a class="sidebar-item" href="#">Item 2</a></li>
                  <li><a class="sidebar-item" href="#">Item 3</a></li>
                  <li><a class="sidebar-item" href="#">Item 4</a></li>
                </ul>                
            </div>         
        </div><!--/span-->
        
        <div class="col-md-6">         
          <div class="container-fluid">
                <h1>Notícias Relacionadas a Direito Previdenciário</h1>
                <p>Postada por Usuário <span class="glyphicon glyphicon-user"></span> Em 20/01/2016 às 07:52pm <span class="glyphicon glyphicon-time"></span></p>
                <br>
                <div style="word-wrap: break-word!important;">
                    Anualmente a Receita Federal define, por meio de parâmetros, quais as Pessoas Físicas e Jurídicas que estarão sujeitas ao acompanhamento diferenciado da fiscalização fazendária. As regras estão em três normas, a saber: a) · Portaria RFB nº 641, de 11 de maio de 2015; b) Portaria RFB nº 1.754, de 24 de dezembro de 2015 (Pessoas Físicas Diferenciadas) e c) Portaria RFB nº 1.755, de 24 de dezembro de 2015 (Pessoas Jurídicas Diferenciadas). Read More »
                </div> 

                <hr>               

                <h1>Another News from Website</h1>
                <p>Postada por Usuário <span class="glyphicon glyphicon-user"></span> Em 21/01/2016 às 11:52am <span class="glyphicon glyphicon-time"></span></p>
                <br>
                <div style="word-wrap: break-word!important;">
                    Anualmente a Receita Federal define, por meio de parâmetros, quais as Pessoas Físicas e Jurídicas que estarão sujeitas ao acompanhamento diferenciado da fiscalização fazendária. As regras estão em três normas, a saber: a) · Portaria RFB nº 641, de 11 de maio de 2015; b) Portaria RFB nº 1.754, de 24 de dezembro de 2015 (Pessoas Físicas Diferenciadas) e c) Portaria RFB nº 1.755, de 24 de dezembro de 2015 (Pessoas Jurídicas Diferenciadas). Read More »
                </div>


          </div>                     
          
          <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

          <hr>
          <footer>                   
                    <div class="container-fluid">
                        <div class="row">                        
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <center>
                                        <h2>Perguntas e Respostas <span class="glyphicon glyphicon-question-sign"></span></h2>
                                    </center>
                                </div>
                                <div class="panel-body" style="font-size: 12px">
                                    <p>O usuário Felipe <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 20/01/2016 às 10:04pm <span class="glyphicon glyphicon-time"></span></b> - <a href="#">Visualizar Resposta</a> <span class="glyphicon glyphicon-ok"></span></p> 
                                    <p>O usuário Welington <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 21/01/2016 às 10:00pm <span class="glyphicon glyphicon-time"></span></b> - <a href="#">Visualizar Resposta</a> <span class="glyphicon glyphicon-ok"></span></p>
                                    <p>O usuário Marcos <span class="glyphicon glyphicon-user"></span> fez uma pergunta <span class="glyphicon glyphicon-question-sign"></span> - Em: 21/01/2016 às 07:00am <span class="glyphicon glyphicon-time"></span></b> - <span style="color: red">Resposta Não Disponível</span> <span class="glyphicon glyphicon-remove"></span></p>
                                </div>
                                <div class="panel-footer"></div>
                            </div>                        
                        </div>                        
                    </div>                
          </footer>
          
      </div><!--/row-->
    </div>
</div><!--/.container-->
            


    </body>


     

</html>
