<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading register-form-title">Gerenciador de Comentários <span class="glyphicon glyphicon-comment"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <th class="text-center">Autor</th>
                    <th class="text-center">Ip do Autor</th>
                    <th class="text-center">Data do Comentário</th>                                        
                    <th class="text-center">Notícia</th>              
                    <th class="text-center">Apagar</th>                    
                    
                    <?php if(empty($comments)): ?>
                        <tr>
                            <center>
                                <h2>Sem comentários no momento! <span class="glyphicon glyphicon-comment"></span></h2>
                            </center>
                        </tr>
                    <?php endif; ?>

                    <?php foreach($comments as $comment): ?>
                        <tr>                        
                            <td class="text-center"><?= $comment->getCommentAuthor(); ?></td>
                            <td class="text-center"><?= $comment->getCommentAuthorIp(); ?></td>                            
                            <td class="text-center"><?= $comment->getCommentDate()->format('d/m/Y - H:i:s'); ?></td>
                            <td class="text-center"><?= $comment->getCommentNews()->getNewsId(); ?></td>
                            <td class="text-center">
                                <a href="<?= $this->url('comments-delete', array('id' => $comment->getCommentId())); ?>">
                                    <button class="btn btn-danger"><span class="glyphicon glyphicon-comment"></span></button>
                                </a>
                            </td>
                            
                            
                        </tr>
                    <?php endforeach; ?>
                    
                </table>
            </div>
         </div>
    </div>
</div>