<div class="container-fluid">
    <div class="panel">
        <div class="panel-heading register-form-title">Gerenciador de Comentários <span class="glyphicon glyphicon-comment"></span></div> 
        
        <div class="panel-body register-form-body" >
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <th class="text-center">Autor</th>
                    <th class="text-center">Data do Comentário</th>                                        
                    <th class="text-center">Notícia</th>                    
                    <th class="text-center">Situação</th>
                    <th class="text-center">Moderar</th>
                    <th class="text-center">Apagar</th>
                    
                    <?php foreach($comments as $comment): ?>
                    <?php endforeach; ?>
                    
                </table>
            </div>
         </div>
    </div>
</div>