

<?php if(empty($news)): ?>
    <div class="container-fluid">
        <center>
            <div class="standard-title">Sem Notícias no Momento! <span class="fa fa-newspaper-o"></span></div>
         </center>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('comments-container').hide();

function toggle(element)
{	
	$(element).is(":visible") ? $(element).slideUp(500) : $(element).slideDown(500);
}

</script>

<div>
    <?php foreach($news as $noticia): ?>
        <div class="container-fluid">
            <div class="news-title"><?= $noticia->getNewsTitle(); ?></div>
            <div class="container-fluid news-container">                
                <p>Postada em <?= $noticia->getNewsDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsDate()->format('H:i'); ?> <span class="glyphicon glyphicon-time"></span> <?php if($noticia->getNewsEditDate() != null):?>|
                    Atualizado em <?= $noticia->getNewsEditDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsEditDate()->format('H:i'); ?> <span style="color: green" class="glyphicon glyphicon-ok"></span>
                <?php endif; ?></p>            
                <br>
                
                <div class="news-font">
                    <?= htmlspecialchars_decode($noticia->getNewsContent()); ?>
                </div>
                
                <div class="news-source">
                    <b>Fonte: <i><a href="<?= $noticia->getNewsSource(); ?>"><?= $noticia->getNewsSource(); ?></a></i></b>
                </div>
                <br>      
                
                <hr>      
                                           
                <br>
             </div>         
         </div> 
    <?php endforeach; ?>

    <div class="container-fluid comments-container form-group" id="<?= 'comment_panel_'.$noticia->getNewsId(); ?>">                   
                        <center>
                            <form style="max-width: 700px" class="panel" method="POST" action="<?= $this->url('comments-add'); ?>">
                                <div class="register-form-title">Digite seu comentário abaixo <span class="glyphicon glyphicon-comment"></span></div>
                                <div class="register-form-body">
                                    <div>                                                                     
                                        <label>Digite seu nome                                
                                            <input required="required" name="comment_author" type="text" class="form-control">
                                        </label>                                        
                                    </div>                                  
                                    
                                    <div>
                                        <label>Digite seu comentário
                                            <textarea name="comment_content" required="required" 
                                            class="form-control comment-input" style="min-width: 600px; min-height: 150px"></textarea>
                                        </label>                            
                                    </div>
                                    <br>

                                    <div><button type="submit" class="btn btn-comment">Comentar <span style="color: #fff"  class="glyphicon glyphicon-comment"></span></button></div><br>
                               </div>
                            </form>
                        </center>  
                        <hr>                    
                        
                            <?php foreach($comentarios as $comment): ?>
                                <p><span style="font-size: 15px" class="glyphicon glyphicon-user"></span> <?= $comment->getCommentAuthor();?> comentou em <?= $comment->getCommentDate()->format('d/m/Y - H:i'); ?> <span class="glyphicon glyphicon-time"></span></p>                                
                                <p><span style="font-size: 17px"><?= $comment->getCommentContent(); ?></span></p>
                                <hr>
                            <?php endforeach; ?>
                                                                 
                </div>                
                
                <center>
                    
                </center>
</div>

   
