<?php if(empty($news)): ?>
    <div class="container-fluid">
        <center>
            <div class="standard-title">Sem Notícias no Momento! <span class="fa fa-newspaper-o"></span></div>
         </center>
    </div>
<?php endif; ?>

<script type="text/javascript">
function comment(id)
{
    var text = document.getElementById("comment_content_"+id).value;
	
	$.ajax({
        type: "POST",         
        url: "<?= $this->url('comments-add'); ?>",
        data: {comment_content: text, comment_news: id},
        success: function(data) {
            alert(data);
        }
    }); 
}
</script>

<?php foreach($news as $noticia): ?>
    <div class="modal fade" id="<?= 'news_'.$noticia->getNewsId(); ?>">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header comment-modal-header">
                    Comentários da Notícia <b><?= $noticia->getNewsTitle() ?> <span style="color: #3399ff;" class="glyphicon glyphicon-comment"></span></b>
                </div>
                <div class="modal-body">
                    <?php if(empty($comments)): ?>
                    
                    <?php else: ?>
                        <?php foreach($comments as $comment): ?>
                        <?php endforeach; ?>
                    <?php endif; ?>               
                </div>
                <div class="modal-footer">
                    <center>
                        <label>Digite seu Comentário abaixo<textarea style="min-width: 400px" class="form-control" id="<?= 'comment_content_'.$noticia->getNewsId(); ?>" name="<?= 'comment_content_'.$noticia->getNewsId(); ?>"  placeholder="digite aqui"></textarea></label>
                        <hr>
                        <button onClick="comment(<?= $noticia->getNewsId(); ?>)" class="btn btn-lg btn-info">Comentar <span class="glyphicon glyphicon-comment"></span></button>
                    </center>
                </div>
            </div>
        </div>
    </div>
<?php endforeach;?>

<?php foreach($news as $noticia): ?>
    <div class="container-fluid">
        <div class="news-title"><?= $noticia->getNewsTitle(); ?></div>
        <div class="container-fluid news-container">                
            <p>Postada em <?= $noticia->getNewsDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsDate()->format('H:i'); ?> <span class="glyphicon glyphicon-time"></span> <?php if($noticia->getNewsEditDate() != null):?>|
                Atualizado em <?= $noticia->getNewsEditDate()->format('d/m/Y'); ?> as <?= $noticia->getNewsEditDate()->format('H:i'); ?> <span style="color: green" class="glyphicon glyphicon-ok"></span>
            <?php endif; ?></p>            
            <br>
            
            <div class="news-font">
                <?= htmlspecialchars_decode($noticia->getNewsContent()); ?>
            </div>
            
            <div class="news-source">
                <b>Fonte: <i><a href="<?= $noticia->getNewsSource(); ?>"><?= $noticia->getNewsSource(); ?></a></i></b>
            </div>
            
            <div>
                <center>
                    <a href="#" data-toggle="modal" data-target="<?= '#news_'.$noticia->getNewsId() ?>">
                        Comentários() <span style="color: blue" class="glyphicon glyphicon-comment"></span>
                    </a>
                </center>
            </div>
            <hr>
         </div>
     </div> 
<?php endforeach; ?>

   
