<center>
    <div class="panel" style="text-align: center">
        <div class="panel-heading register-form-title">Editando Usuário <?= $user->getUserName(); ?> <span class="glyphicon glyphicon-user"></span></div>
        <div class="panel-body register-form-body">    
            <?= $this->form()->openTag($editForm); ?>
            
            <div>
                <label>Login
                    <input class="form-control" type="text" name="user_login" value="<?php echo $user->getUserLogin(); ?>" placeholder="Login">
                </label>
            </div>            
            
            <div>
                <label>Nome do Usuário
                    <input class="form-control" type="text" name="user_name" value="<?php echo $user->getUserName(); ?>" placeholder="Nome do Usuário">
                </label>
            </div>
            
            <div>
                <label>Email
                    <input class="form-control" type="email" name="user_email" value="<?php echo $user->getUserEmail(); ?>" placeholder="Email">
                </label>
            </div>
            
            <div>
                <label>Endereço de IP
                    <input class="form-control" type="text" name="user_ip" value="<?php echo $user->getUserIp()?>" placeholder="Endereço de IP">
                </label>
            </div>
            
            <div>
                <label>Perfil
                    <select class="form-control" name="user_profile">
                        <option value="<?php echo $user->getUserProfile();?>"><?php echo $user->getUserProfile();?></option>
                        <?php foreach($profiles as $profile): ?> 
                            <?php if($profile != $user->getUserProfile()): ?>
                                <option value="<?php echo $profile ?>"><?php echo $profile ?></option>
                            <?php endif; ?>                           
                        <?php endforeach; ?>
                    </select>
                </label>
            </div>
            
            <div>
                <label>Senha (caso não queira alterar, deixe vazio)
                    <input class="form-control" type="password" name="user_password" placeholder="Senha">
                </label>
            </div>
            
            <br>
            <div><button type="submit" class="btn btn-lg btn-success" >Salvar <span class="fa fa-check"></span></button></div>
            <?= $this->form()->closeTag(); ?>        
        </div>
    </div>
</center>