<div class="table-responsive">
    
    <center>
        <div class="standard-title">Controle de Usuários <span class="glyphicon glyphicon-user"></span></div>
    </center>  
    <hr>  
    
    <table class="table table-striped">        
        <th>Login</th>
        <th>Email</th>
        <th>Nome</th>
        <th>Data de Cadastro</th>
        <th>Último Acesso</th>
        <th>Endereço de IP</th>
        <th>Perfil</th>        
        <th>Editar</th>
        <th>Apagar</th>
        <th>Bloquear Acesso</th>
        
        <?php foreach($users as $user): ?>
            <tr>                
                <td><?= $user->getUserLogin(); ?></td>
                <td><?= $user->getUserEmail(); ?></td>
                <td><?= $user->getUserName(); ?></td>
                <td><?= $user->getUserRegisterDate()->format('d/m/Y - H:i:s'); ?></td>                
                <td><?= $user->getUserLastLogin()->format('d/m/Y - H:i:s'); ?></td>
                <td><?= $user->getUserIp(); ?></td>
                <td><?= $user->getUserProfile(); ?></td>                
                <td>
                    <a href="<?php echo $this->url('users-edit', array('id' => $user->getUserId())); ?>">   
                        <button class="btn btn-info"><span class='glyphicon glyphicon-pencil'></span></button>                     
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url('users-delete', array('id' => $user->getUserId())); ?>">   
                        <button class="btn btn-danger"><span class='glyphicon glyphicon-remove'></span></button>                     
                    </a>
                </td>
                <td>
                    <a href="<?php echo $this->url( ($user->isUserBlocked() ? 'users-unblock' : 'users-block'), array('id' => $user->getUserId())); ?>"> 
                        <button class="btn btn-primary">
                        <?php echo($user->isUserBlocked() ? "Desbloquear" : "Bloquear")?>
                        </button>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>